name: Platform
version: 1.0
main: org.platform.Platform
author: Muvixo
description: Simple cosmetic PvP platform plugin
commands:
  platform:
    description: Main Platform command
    usage: /platform <kit|setspawn|creator|cc|sb|reload|help>
    aliases:
      - pf
permissions:
  platform.kit:
    description: Allows giving the cosmetic kit
    default: op
  platform.setspawn:
    description: Allows setting the spawn point
    default: op
  platform.connection:
    description: Allows managing the connection check
    default: op
  platform.reload:
    description: Allows reloading the config
    default: op
  platform.scoreboard.toggle:
    description: Allows toggling the scoreboard
    default: true

  # ---- Protection ----
  platform.bypass:
    description: Bypass ALL protection (break, place, drop)
    default: op
  platform.break:
    description: Allows breaking map blocks
    default: false
  platform.place:
    description: Allows placing blocks
    default: false
  platform.drop:
    description: Allows dropping items
    default: false
